version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pswdrd123
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080
      
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/usr/src/app